# 6장 단순한 1010 패턴 - 생성기 결과 확인하기 (p124)

### 중앙대학교 첨단영상대학원 영상학과 - 딥러닝 시각효과

In [1]:
import torch
import torch.nn as nn

In [2]:
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.model = nn.Sequential(
        nn.Linear(1, 3),
        nn.Sigmoid(),
        nn.Linear(3, 4),
        nn.Sigmoid()
        )
        
        self.optimizer = torch.optim.SGD(self.parameters(), lr=0.01)
        
        self.counter = 0;
        self.progress = []
        
    def forward(self, inputs):
        return self.model(inputs)
        

In [3]:
G = Generator()

In [4]:
G.forward(torch.FloatTensor([0.5]))

tensor([0.6272, 0.3750, 0.5556, 0.3042], grad_fn=<SigmoidBackward>)

In [5]:
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.model = nn.Functional(
        nn.Linear(1, 3),
        nn.Sigmoid(),
        nn.Linear(3, 4),
        nn.Sigmoid()
        )
        
        self.optimizer = torch.optim.SGD(self.parameters(), lr=0.01)
        
        self.counter = 0;
        self.progress = []
        
    def forward(self, inputs):
        return self.model(inputs)

In [6]:
model = nn.Linear(1,3)(torch.FloatTensor([5]))
print(model)

tensor([ 4.4872, -0.2266,  0.2303], grad_fn=<AddBackward0>)


In [7]:
model = nn.Sigmoid()(model)
print(model)

tensor([0.9889, 0.4436, 0.5573], grad_fn=<SigmoidBackward>)


In [8]:
model = nn.Linear(3,4)(model)
print(model)

tensor([-0.3957, -0.5087,  0.0752,  0.5863], grad_fn=<AddBackward0>)


In [9]:
model = nn.Sigmoid()(model)
print(model)

tensor([0.4023, 0.3755, 0.5188, 0.6425], grad_fn=<SigmoidBackward>)
